services:
  - type: web
    name: tg-power
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: tg_power
      - key: OWNER_ID
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: MAX_BOTS_PER_USER
        value: "5"
      - key: MAX_FILE_SIZE_MB
        value: "2000"
      - key: MAX_VIDEO_DURATION_SECONDS
        value: "1800"

      - key: USER_SESSION
        sync: false
      - key: ENABLE_BOTFATHER_AUTOMATION
        value: "true"
