services:
  - type: web
    name: tg-power
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: USER_SESSION
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: tg_power_db
      - key: YOUTUBE_COOKIES_BASE64
        sync: false
      - key: YOUTUBE_PO_TOKEN
        sync: false
